### ISSUE TITLE
Rename interfaces and methods

### ISSUE THREAD

**Issue by dmolineus** [phpcq/plugin-api#1]
- [x] Rename `BuildConfigInterface` to `BuildEnvironmentInterface`
- [x] Remove `processConfig` to `ConfigurationPluginInterface`
- [x] Implement `TaskRunnerInterface` with `createTasks` (formerly `ConfigurationPluginInterface::processConfig`)
- [x] Rename `TaskRunnerInterface` to `TaskInterface`
- [x] Rename`ToolReportInterface::addError` to `addDiagnostic`
- [x] `addDiagnostic` should return `DiagnosticBuilderInterface` (#2)

**Comment by discordier** [comment]
While we are at it, we definitely have to replace the array in `ConfigurationPluginInterface::processConfig(array $config, BuildConfigInterface $buildConfig): iterable` with a config reader or the like.
