### ISSUE TITLE
Report expansion - additional fields

### ISSUE THREAD

**Issue by discordier** [phpcq/plugin-api#4]
As per https://github.com/phpcq/plugin-api/pull/3#discussion_r434634838, we want to add `classname` support to the  `DiagnosticBuilderInterface`.

This should ideally be implemented as a `list<string>`, as a diagnostic might refer to multiple classes.

**Comment by dmolineus** [comment]
Also add a category would be helpful to categorize diagnostics, e.g. `tests`, `codestyle`, `static-analysis`, ...
